jubatus/jubatus-example

- README.md
- trivial_burst/config.json
- trivial_burst/python/burst_dummy_stream.py
I wrote a simple burst example.
> add trivial_burst

- twitter_streaming_location/python/train.py
Remove an import statement which attemts to import a removed name.
> Remove an import statement which attemts to import a removed name.

- twitter_streaming_location/java/src/main/java/example/twitterstreaminglocation/LocationClassifierApp.java
- twitter_streaming_location/java/src/main/java/example/twitterstreaminglocation/LocationTrainerApp.java
> fix twitter_streaming_location Java compile error (fix #35)

- gender/python/gender.py
> fix gender for python 3 support

- README.md
recommender -> regression in winequality row.
> Fix a table in README.

- movielens/cpp/ml_analysis.cpp
- movielens/cpp/ml_update.cpp
- movielens/cpp/wscript
fix movielens example to remove dependency on pficommon
> fix movielens to remove dependency on pficommon

- movielens/python/ml_analysis.py
- movielens/python/ml_update.py
fix movielens example to support python 2 and 3
> fix movielens for python3

- trivial_stat/python/stat.py
fix trivial_stat example to support python 2 and 3
ref #41
> fix stat example for py3

- winequality/ruby/test.rb
- winequality/ruby/train.rb
> Fix winequality ruby example to train/test properly.

- README.md
I have updated the README.md file to include the bandit example.
Related #47.
> add bandit example to example summary

- npb_similar_player/python/analyze.py
> fix npb_similar_player for python 3

- npb_similar_player/cpp/analyze.cpp
- npb_similar_player/cpp/update.cpp
- npb_similar_player/cpp/wscript
- npb_similar_player/normalize_plugin/src/normalize_num_feature.cpp
- npb_similar_player/normalize_plugin/src/normalize_num_feature.hpp
- npb_similar_player/normalize_plugin/src/normalize_num_filter.cpp
- npb_similar_player/normalize_plugin/src/normalize_num_filter.hpp
- npb_similar_player/normalize_plugin/src/wscript
- npb_similar_player/normalize_plugin/wscript
> eliminate pficommon in npb_similar_player example (refs #17)

- train_route/python/create_graph.py
- train_route/python/search_route.py
> Fix train_route for python 3

- rent/python/jubahomes.py
> Fix rent for Python 3

- language_detection/python/test.py
- language_detection/python/train.py
fix language_detection example to support python 2 and 3
> fix language_detection for Python3

- malware_classification/cpp/word_ngram_plugin/wscript
- malware_classification/cpp/wscript
- movielens/cpp/wscript
- npb_similar_player/cpp/wscript
- npb_similar_player/normalize_plugin/src/wscript
- npb_similar_player/normalize_plugin/wscript
- shogun/cpp/wscript
> modernize wscript files (fix #44)

- twitter_streaming_location/python/classify.py
- twitter_streaming_location/python/train.py
> fix twitter_streaming_location for python 3 support

- twitter_streaming_lang/python/classify-twitter-stream.py
- twitter_streaming_lang/python/train-wiki-abstract.py
> fix twitter_streaming_lang for python 3

- README.md
- network_intrusion_detection/README.md
- network_intrusion_detection/config.json
- network_intrusion_detection/python/anomaly.py
- network_intrusion_detection/ruby/anomaly.rb
add python and ruby examples that work jubatus 0.8.9.
> Add anomaly example

- network_intrusion_detection/config.json
Refs https://github.com/jubatus/jubatus_core/pull/265
> (develop) remove retain_projection option

- rent/rent.json
- winequality/config.json
Fixes https://github.com/jubatus/jubatus-example/issues/86
> Fix regression sample

- malware_classification/cpp/ml_classify.cpp
> fix wrong codes in ml_classification

- AAAI/README.md
- AAAI/aaai.json
- AAAI/python/README.md
- AAAI/python/analyze.py
- AAAI/python/set_row.py
- README.md
> add NN example(AAAI)

- mnist/python/jubamnist.py
> fix jubamnist to work with Python 2.6
